#!/bin/bash

#set -x

TIMEDIR=~/.timeprivacy

SECONDS_FILE="$TIMEDIR/seconds_file_"$1""
MINUTES_FILE="$TIMEDIR/minutes_file_"$1""
HOURS_FILE="$TIMEDIR/hours_file_"$1""

#DAYS_FILE="$TIMEDIR/days_file_"$1""
#MONTHS_FILE="$TIMEDIR/months_file_"$1""
#YEARS_FILE="$TIMEDIR/years_file_"$1""

read_date_file() {
   if [ ! -d "$TIMEDIR" ]; then
      mkdir -p "$TIMEDIR"
   fi

   if [ ! -f "$SECONDS_FILE" ]; then
      echo "0" > "$SECONDS_FILE"
   fi

   if [ ! -f "$MINUTES_FILE" ]; then
      echo "0" > "$MINUTES_FILE"
   fi

   if [ ! -f "$HOURS_FILE" ]; then
      echo "0" > "$HOURS_FILE"
   fi

   #if [ ! -f "$DAYS_FILE" ]; then
      #echo "1" > "$DAYS_FILE"
   #fi

   #if [ ! -f "$MONTHS_FILE" ]; then
      #echo "1" > "$MONTHS_FILE"
   #fi

   #if [ ! -f "$YEARS_FILE" ]; then
      #echo "2013" > "$YEARS_FILE"
   #fi

   SECONDS="$(cat "$SECONDS_FILE")"
   MINUTES="$(cat "$MINUTES_FILE")"
   HOURS="$(cat "$HOURS_FILE")"

   if [ -z "$SECONDS" ]; then
      SECONDS="0"
   fi

   if [ -z "$MINUTES" ]; then
      MINUTES="0"
   fi

   if [ -z "$HOURS" ]; then
      HOURS="0"
   fi

   local nodigits="$(echo $SECONDS | sed 's/[[:digit:]]//g')"
   if [ ! -z "$nodigits" ]; then
      SECONDS="0"
   fi

   local nodigits="$(echo $MINUTES | sed 's/[[:digit:]]//g')"
   if [ ! -z "$nodigits" ]; then
      MINUTES="0"
   fi

   local nodigits="$(echo $HOURS | sed 's/[[:digit:]]//g')"
   if [ ! -z "$nodigits" ]; then
      HOURS="0"
   fi

   SECONDS="$(expr "$SECONDS" + "1")" || true
   if [ "$SECONDS" -ge "60" ]; then
      SECONDS="0"

      MINUTES="$(expr "$MINUTES" + "1")" || true
      if [ "$MINUTES" -ge "60" ]; then
         MINUTES="0"

         HOURS="$(expr "$HOURS" + "1")" || true
         if [ "$HOURS" -ge "24" ]; then
            HOURS="0"
         fi
         echo "$HOURS" > "$HOURS_FILE"

      fi
      echo "$MINUTES" > "$MINUTES_FILE"

   fi

   echo "$SECONDS" > "$SECONDS_FILE"

   #echo "$HOURS $MINUTES $SECONDS"
}

need_new_date() {
   ## Testing
   #while [ 1 ]; do
   #   read_date_file
   #done

   _day="$(date +"%d")"
   _month="$(date +"%m")"
   _year="$(date +"%Y")"

   #_hour="$(date +"%H")"
   #_minute="$(date +"%M")"
   #_second="$(date +"%S")"

   read_date_file

   ## Testing
   #echo "faketime '$_year-$_month-$_day $HOURS:$MINUTES:$SECONDS' /bin/date"
   #faketime "$_year-$_month-$_day $HOURS:$MINUTES:$SECONDS" /bin/date

   echo "$_year-$_month-$_day $HOURS:$MINUTES:$SECONDS"
}

need_new_date

